server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://1.234.44.77:3306/mysql
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: aop
  security:
    user:
      name: admin
      password: 1234